# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - test-publish

env:
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci

      - name: Setup Git config
        run: |
          git config --global user.name 'Devo GitHub Action'
          git config --global user.email 'desa@devo.com'

      - name: Publish version to NPM
      - run: NODE_AUTH_TOKEN=${{secrets.NPM_TOKEN}} npm publish

      - uses: webiny/action-post-run@2.0.1
        id: another-post-run-command
        with:
          run: find /home/runner/.npm/_logs/ -type f | xargs tail -n +1
      # - run: npm ci
      # - run: echo 'config'
      # - run: npm get config
      # - run: echo 'config2'
      # - run: npm config list
      # - run: echo 'config3'
      # - run: cat /home/runner/work/_temp/.npmrc
      # - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
